//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOCSoftware.Utilities.PortInspector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MOCSoftware.Utilities.PortInspector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richard Chown.
        /// </summary>
        public static string About_Author {
            get {
                return ResourceManager.GetString("About_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string About_AuthorLabel {
            get {
                return ResourceManager.GetString("About_AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string About_CompanyLabel {
            get {
                return ResourceManager.GetString("About_CompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string About_CopyrightLabel {
            get {
                return ResourceManager.GetString("About_CopyrightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Inspector is a simple TCP/UDP network port scanner..
        /// </summary>
        public static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string About_DescriptionLabel {
            get {
                return ResourceManager.GetString("About_DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Port Inspector.
        /// </summary>
        public static string About_Header {
            get {
                return ResourceManager.GetString("About_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Inspector.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string About_TitleLabel {
            get {
                return ResourceManager.GetString("About_TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string About_VersionLabel {
            get {
                return ResourceManager.GetString("About_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add the host {0}. .
        /// </summary>
        public static string AddHostErrorMessage {
            get {
                return ResourceManager.GetString("AddHostErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Adding Host.
        /// </summary>
        public static string AddHostErrorMessageTitle {
            get {
                return ResourceManager.GetString("AddHostErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Host List.
        /// </summary>
        public static string AddHostListView_Title {
            get {
                return ResourceManager.GetString("AddHostListView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a list of hosts to inspect. One host name per line..
        /// </summary>
        public static string AddHostListView_ToolTip {
            get {
                return ResourceManager.GetString("AddHostListView_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Host.
        /// </summary>
        public static string AddHostRemoveButtonToolTip {
            get {
                return ResourceManager.GetString("AddHostRemoveButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string AddHostView_AddButton {
            get {
                return ResourceManager.GetString("AddHostView_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string AddHostView_CancelButton {
            get {
                return ResourceManager.GetString("AddHostView_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Port.
        /// </summary>
        public static string AddPortWindowTitle {
            get {
                return ResourceManager.GetString("AddPortWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Port.
        /// </summary>
        public static string EditPortWindowTitle {
            get {
                return ResourceManager.GetString("EditPortWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Data.
        /// </summary>
        public static string Error_DataLoad_Title {
            get {
                return ResourceManager.GetString("Error_DataLoad_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A port ({0}) with the specified port number ({1}) and protocol ({2}) already exists in the list. .
        /// </summary>
        public static string Error_DuplicatePort_Message {
            get {
                return ResourceManager.GetString("Error_DuplicatePort_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Port.
        /// </summary>
        public static string Error_DuplicatePort_Title {
            get {
                return ResourceManager.GetString("Error_DuplicatePort_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred attempting to load the host list from file: {0}.
        /// </summary>
        public static string ErrorMessageHostLoadText {
            get {
                return ResourceManager.GetString("ErrorMessageHostLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading host list.
        /// </summary>
        public static string ErrorMessageHostLoadTitle {
            get {
                return ResourceManager.GetString("ErrorMessageHostLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred attempting to save the host list to file:{0}.
        /// </summary>
        public static string ErrorMessageHostSaveText {
            get {
                return ResourceManager.GetString("ErrorMessageHostSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving host list.
        /// </summary>
        public static string ErrorMessageHostSaveTitle {
            get {
                return ResourceManager.GetString("ErrorMessageHostSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Host List.
        /// </summary>
        public static string HostDataPersistor_FileLoadDialogTitle {
            get {
                return ResourceManager.GetString("HostDataPersistor_FileLoadDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Host List.
        /// </summary>
        public static string HostDataPersistor_FileSaveDialogTitle {
            get {
                return ResourceManager.GetString("HostDataPersistor_FileSaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve host name or IP Address: {0}.
        /// </summary>
        public static string HostInfo_ResolutionErrorMessage {
            get {
                return ResourceManager.GetString("HostInfo_ResolutionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving....
        /// </summary>
        public static string HostInfo_ResolvingMessage {
            get {
                return ResourceManager.GetString("HostInfo_ResolvingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _Host List.
        /// </summary>
        public static string HostListView_AddMany {
            get {
                return ResourceManager.GetString("HostListView_AddMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Abort Scan.
        /// </summary>
        public static string HostListView_CancelButton {
            get {
                return ResourceManager.GetString("HostListView_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add Host.
        /// </summary>
        public static string HostListView_HostAddButton {
            get {
                return ResourceManager.GetString("HostListView_HostAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Host Name or IP Address.
        /// </summary>
        public static string HostListView_HostAddLabel {
            get {
                return ResourceManager.GetString("HostListView_HostAddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Query Ports on Hosts.
        /// </summary>
        public static string HostListView_InspectButton {
            get {
                return ResourceManager.GetString("HostListView_InspectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove Host.
        /// </summary>
        public static string HostListView_RemoveHost {
            get {
                return ResourceManager.GetString("HostListView_RemoveHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        public static string HostListViewModel_ScanningMessage {
            get {
                return ResourceManager.GetString("HostListViewModel_ScanningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ok.
        /// </summary>
        public static string MessageDialog_OkButtonText {
            get {
                return ResourceManager.GetString("MessageDialog_OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Port Name.
        /// </summary>
        public static string PortAddPortNameLabel {
            get {
                return ResourceManager.GetString("PortAddPortNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a friendly name for the port.
        /// </summary>
        public static string PortAddPortNameValidationErrorMessage {
            get {
                return ResourceManager.GetString("PortAddPortNameValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_ort Number.
        /// </summary>
        public static string PortAddPortNumberLabel {
            get {
                return ResourceManager.GetString("PortAddPortNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a port number between 0  and 65535.
        /// </summary>
        public static string PortAddPortNumberValidationMessage {
            get {
                return ResourceManager.GetString("PortAddPortNumberValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_rotocol.
        /// </summary>
        public static string PortAddProtocolLabel {
            get {
                return ResourceManager.GetString("PortAddProtocolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hosts.
        /// </summary>
        public static string PortListView_HostLabel {
            get {
                return ResourceManager.GetString("PortListView_HostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port F_ilter.
        /// </summary>
        public static string PortListView_PortFilterLabel {
            get {
                return ResourceManager.GetString("PortListView_PortFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ports.
        /// </summary>
        public static string PortListView_PortsLabel {
            get {
                return ResourceManager.GetString("PortListView_PortsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_rotocol.
        /// </summary>
        public static string PortListView_ProtocolLabel {
            get {
                return ResourceManager.GetString("PortListView_ProtocolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string StatusMessageError {
            get {
                return ResourceManager.GetString("StatusMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading port data....
        /// </summary>
        public static string StatusMessageLoadingData {
            get {
                return ResourceManager.GetString("StatusMessageLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading host list....
        /// </summary>
        public static string StatusMessageLoadingHosts {
            get {
                return ResourceManager.GetString("StatusMessageLoadingHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving port data....
        /// </summary>
        public static string StatusMessageSavingData {
            get {
                return ResourceManager.GetString("StatusMessageSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving host list....
        /// </summary>
        public static string StatusMessageSavingHosts {
            get {
                return ResourceManager.GetString("StatusMessageSavingHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string TcpSocketInfo_ScanResultOkMessage {
            get {
                return ResourceManager.GetString("TcpSocketInfo_ScanResultOkMessage", resourceCulture);
            }
        }
    }
}
